package org.wahid.borutoappversion1.ui.theme

import androidx.compose.ui.unit.dp

val STARS_SPACE_BY_VALUE = 6.dp
val HERO_HOME_ITEM_HEIGHT = 500.dp
val ROUNDED_CORNER_SIZE = 16.dp
val MEDIUM_ROUNDED_CORNER_SIZE = 10.dp
val SMALL_ROUNDED_CORNER_SIZE = 8.dp
val LARGE_PADDING = 40.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val SHIMMER_NAME_PLACEHOLDER_ITEM = 20.dp
val SHIMMER_ABOUT_PLACEHOLDER_ITEM = 12.dp
val SHIMMER_STAR_PLACEHOLDER_ITEM_SIZE = 20.dp
val ERROR_ICON_SIZE = 120.dp
val SEARCH_TOP_BAR_HEIGHT = 70.dp
val SEARCH_TOP_BAR_CORNER_SIZE = 12.dp
val SHIMMER_STAR_CORNER_SIZE = 3.dp

